### PR TITLE
Fix the fetching of solver stats

### LINKED ISSUE #184: add a flag to print the solver statistics
the quick&dirty way to do it for reference:

```patch
diff --git a/src/symbolic_choice.ml b/src/symbolic_choice.ml
index e799358..534a023 100644
--- a/src/symbolic_choice.ml
+++ b/src/symbolic_choice.ml
@@ -19,7 +19,10 @@ let check sym_bool thread (S (solver_module, solver)) =
   | _ ->
     let check = no :: pc in
     let module Solver = (val solver_module) in
+
     let r = Solver.check solver check in
+        Solver.pp_statistics Stdlib.Format.std_formatter solver;
+        Stdlib.Format.pp_print_flush Stdlib.Format.std_formatter ();
     not r
 
 let list_select b ({ Thread.pc; _ } as thread) (S (solver_module, s)) =
@@ -34,6 +37,9 @@ let list_select b ({ Thread.pc; _ } as thread) (S (solver_module, s)) =
     let with_not_v = Bool.not v :: pc in
     let sat_true = Solver.check s with_v in
     let sat_false = Solver.check s with_not_v in
+
+        Solver.pp_statistics Stdlib.Format.std_formatter s;
+        Stdlib.Format.pp_print_flush Stdlib.Format.std_formatter ();
     match (sat_true, sat_false) with
     | false, false -> []
     | true, false | false, true -> [ (sat_true, thread) ]
@@ -78,6 +84,8 @@ let list_select_i32 sym_int thread (S (solver_module, solver)) =
       if not (Solver.check solver (additionnal @ pc)) then []
       else begin
         let model = Solver.model ~symbols:[ symbol ] solver in
+        Solver.pp_statistics Stdlib.Format.std_formatter solver;
+        Stdlib.Format.pp_print_flush Stdlib.Format.std_formatter ();
         match model with
         | None -> assert false (* ? *)
         | Some model -> (
```

### PR DESCRIPTION
**Pull request by hra687261**
This PR attempts to fix the fetching of statistics that was added #797 by making sure that the statistics of all the used solver are fetched.
That is done by keeping in a global list every solver instance that was created and iterating over that list to get all their stats when `--bench` is enabled.
In some cases this causes a segmentation fault (when using multiple workers), I am not yet sure why but I suspect Z3 does not like being asked for statistics while it is still running (this can happen we found a bug and we try to fetch stats from a domain that is still running, and what is running in that domain in Z3),

Closes #184

### CODE REVIEW

**Comment by hra687261** [comment]
After rebasing the CI does not pass since the version of smtml changed :/

File: src/symbolic/solver.ml [hunk 1]
```diff
@@ -6,13 +6,20 @@ type 'a solver_module = (module Smtml.Solver_intf.S with type t = 'a)
...
   let module Mapping = Mapping.Fresh.Make () in
   let module Batch = Smtml.Solver.Cached (Mapping) in
-  let solver = Batch.create ~logic:QF_BVFP () in
-  S ((module Batch), solver)
+  let solver_inst = Batch.create ~logic:QF_BVFP () in
+  let solver = S ((module Batch), solver_inst) in
+  ( if Log.is_bench_enabled () then
+      let l = Atomic.get instances in
+      let l = solver :: l in
+      Atomic.set instances l );
```
Comment (redianthus) [inline src/symbolic/solver.ml]: I think this is actually not right. You should either use `Atomic.compare_and_set` or a `Mutex.t`, otherwise, this could be racy and loose some solvers along the way

Comment (hra687261) [reply src/symbolic/solver.ml]: Indeed, fixed!
